### ISSUE TITLE
Receiving 500 error (Internal Server Error)

### ISSUE THREAD

**Issue by BritishBenji** [SuperSonicHub1/TikTok-RSS#1]
Receiving this error:
```py 
[2021-11-11 20:27:58,369] ERROR in app: Exception on /feed/LindseyStirling [GET]
Traceback (most recent call last):
  File "C:\Users\-\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\-\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\-\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\-\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\-\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\-\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1935, in dispatch_request     
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\Users\-\Desktop\TikTok-RSS\main.py", line 16, in feed
    feed = generate_feed(username)
  File "c:\Users\-\Desktop\TikTok-RSS\generator.py", line 31, in generate_feed
    next_data = loads(json_element.text())
AttributeError: 'NoneType' object has no attribute 'text'
192.168.0.10 - - [11/Nov/2021 20:27:58] "GET /feed/LindseyStirling HTTP/1.1" 500 -
```

Unsure if this has anything to do with TikTok starting to Issue Catpha's? 
Either way, erroring out from multiple hosts, unable to scrape the data

**Comment by SuperSonicHub1** [comment]
Someone's actually using this? I'll check it out in an hour; I was
wondering why my feeds have been empty for a few days now.

**Comment by SuperSonicHub1** [comment]
Needed to update my Cookie header, should be fixed now.
