### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by SuperSonicHub1** [SuperSonicHub1/TikTok-RSS#8]
It's broken *again*! Hooray! It seems that the issue is now that responses are now empty, meaning that parsing the response fails.

yt-dlp issue: https://github.com/yt-dlp/yt-dlp/issues/3776#issuecomment-1190564993

Traceback:
```
[2022-07-22 15:30:06,387] ERROR in app: Exception on /feed/emiru [GET]
Traceback (most recent call last):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "main.py", line 23, in feed
    feed = generate_feed(username)
  File "/home/runner/TikTok-RSS/generator.py", line 55, in generate_feed
    body = client.get_user(username.lower())
  File "/home/runner/TikTok-RSS/client.py", line 112, in get_user
    return call_api("aweme/post", params)
  File "/home/runner/TikTok-RSS/client.py", line 96, in call_api
    return res.json()
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by SuperSonicHub1** [comment]
I've lost interest in this project; I no longer crave short-term content.
